package io.jenkins.plugins.analysis.core.graphs;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.assertj.core.api.ListAssert;
import org.jfree.data.category.CategoryDataset;
import org.junit.jupiter.api.Test;

import edu.hm.hafner.analysis.Priority;
import io.jenkins.plugins.analysis.core.quality.HealthDescriptor;
import io.jenkins.plugins.analysis.core.quality.StaticAnalysisRun;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.Mockito.*;

class HealthSeriesBuilderTest {

    /**
     * testComputeSeries should return a list with a zero, if the unhealthy is not bigger than healthy
     * healthy == unhealthy
     * result: (0)
     */
    @Test
    void computeSeriesHealthDescriptorDisabled() {
        assertThat(testComputeSeries(1, 1, 0)).containsExactly(0);
    }

    /**
     * total == healthy < unhealthy
     * result: (healty, 0, 0)
     */
    @Test
    void computeSeriesTotalEqualToHealthy() {
        assertThat(testComputeSeries(1, 3, 1)).containsExactly(1, 0, 0);
    }

    /**
     * healthy < unhealthy == total
     * result: (healty, unhealthy - healthy ,0)
     */
    @Test
    void computeSeriesTotalEqualToUnhealty() {
        assertThat(testComputeSeries(1, 3, 3)).containsExactly(1, 2, 0);
    }

    /**
     * healthy < unhealthy < total
     * result: (healty, unhealthy - healthy, total - unhealthy)
     */
    @Test
    void computeSeriesTotalBiggerThanUnhealthy() {
        assertThat(testComputeSeries(1, 3, 6)).containsExactly(1, 2, 3);
    }

    @Test
    void t1() {
        int healthy = 0;
        int unHeahlthy = 1;
        int total = 0;

        HealthDescriptor healthDescriptor = new HealthDescriptor(Integer.toString(healthy), Integer.toString(unHeahlthy), Priority.NORMAL);
        StaticAnalysisRun staticAnalysisRun = mock(StaticAnalysisRun.class);
        when(staticAnalysisRun.getTotalSize()).thenReturn(total);
        HealthSeriesBuilder sut = new HealthSeriesBuilder(healthDescriptor);

        List<StaticAnalysisRun> staticAnalysisRuns = new ArrayList<>();
        staticAnalysisRuns.add(0, mock(StaticAnalysisRun.class));
        //when(staticAnalysisRuns.get(0))

        GraphConfiguration graphConfiguration = mock(GraphConfiguration.class);
        when(graphConfiguration.useBuildDateAsDomain()).thenReturn(false);
        when(graphConfiguration.isDayCountDefined()).thenReturn(false); // Needed in areResultsTooOld()
        CategoryDataset result = sut.createDataSet(graphConfiguration, staticAnalysisRuns);

    }

    /**
     * Runs a parameterized test of computeSeriesGraphConfiguration
     * @param healthy healthy parameter
     * @param unHeahlthy unhealthy parameter
     * @param total total parameter
     * @return the list generated by computeSeries
     */
    private List<Integer> testComputeSeries(int healthy, int unHeahlthy, int total) {
        HealthDescriptor healthDescriptor = new HealthDescriptor(Integer.toString(healthy), Integer.toString(unHeahlthy), Priority.NORMAL);
        StaticAnalysisRun staticAnalysisRun = mock(StaticAnalysisRun.class);
        when(staticAnalysisRun.getTotalSize()).thenReturn(total);
        HealthSeriesBuilder sut = new HealthSeriesBuilder(healthDescriptor);
        return sut.computeSeries(staticAnalysisRun);
    }
}